"""Topic vocabularies used by deterministic corpus pre-screening."""

from __future__ import annotations

SYSTEMS_NEUROIMAGING_TERMS = [
    "fMRI",
    "functional MRI",
    "BOLD",
    "resting-state",
    "resting state",
    "neuroimaging",
    "functional connectivity",
    "effective connectivity",
    "dynamic connectivity",
    "connectome",
]
SYSTEMS_NETWORK_TERMS = [
    "default mode network",
    "DMN",
    "salience network",
    "frontoparietal network",
    "central executive network",
    "limbic network",
    "visual network",
    "sensorimotor network",
    "global brain connectivity",
    "network integrity",
    "network modularity",
    "desynchronization",
    "desynchronisation",
]

SYSTEMS_REGION_TERMS = [
    "prefrontal cortex",
    "medial prefrontal cortex",
    "mPFC",
    "orbitofrontal cortex",
    "anterior cingulate cortex",
    "posterior cingulate cortex",
    "hippocampus",
    "amygdala",
    "thalamus",
    "claustrum",
    "striatum",
    "nucleus accumbens",
    "dorsal raphe nucleus",
    "insula",
]

SYSTEMS_CIRCUIT_TERMS = [
    "brain region",
    "brain circuit",
    "circuit",
    "thalamo-cortical",
    "thalamocortical",
    "cortico-striatal",
    "corticostriatal",
    "cortical-subcortical",
    "fronto-limbic",
    "corticolimbic",
    "hippocampal-prefrontal",
    "amygdala-prefrontal",
    "mesolimbic",
    "reward circuit",
]

PET_OCCUPANCY_TERMS = [
    "PET",
    "positron emission tomography",
    "receptor occupancy",
    "occupancy",
    "radioligand",
    "FDG",
    "glucose metabolism",
    "cerebral blood flow",
    "arterial spin labeling",
    "CBF",
]

EEG_MEG_NEUROPHYS_TERMS = [
    "EEG",
    "MEG",
    "electroencephalography",
    "magnetoencephalography",
    "neural oscillations",
    "oscillatory",
    "event-related potential",
    "ERP",
    "gamma",
    "theta",
    "alpha",
    "signal diversity",
    "entropy",
    "Lempel-Ziv",
    "electrophysiology",
]

COGNITIVE_AFFECTIVE_TASK_TERMS = [
    "cognitive flexibility",
    "reversal learning",
    "probabilistic reversal learning",
    "set shifting",
    "attentional set shifting",
    "fear conditioning",
    "fear extinction",
    "extinction learning",
    "reward learning",
    "reinforcement learning",
    "emotional processing",
    "emotion recognition",
    "social cognition",
    "social reward learning",
    "attention",
    "impulsivity",
    "prepulse inhibition",
]

TRANSLATIONAL_BEHAVIOR_TERMS = [
    "forced swim test",
    "tail suspension test",
    "learned helplessness",
    "chronic social defeat",
    "open field",
    "elevated plus maze",
    "sucrose preference",
    "conditioned place preference",
    "self-administration",
    "drug seeking",
    "conditioned freezing",
]

TASK_EVIDENCE_TERMS = [
    "task",
    "behavior",
    "behaviour",
    "behavioral",
    "behavioural",
    "performance",
    "learning",
    "conditioning",
    "response",
    "paradigm",
]

PRECLINICAL_EVIDENCE_TERMS = [
    "mouse",
    "mice",
    "rat",
    "rodent",
    "animal model",
    "behavioral assay",
    "behavioural assay",
    "in vivo",
    "neuronal activity",
    "c-Fos",
]

MOLECULAR_PATHWAY_TERMS = [
    "BDNF",
    "TrkB",
    "NTRK2",
    "mTOR",
    "ERK",
    "MAPK",
    "CREB",
    "Akt",
    "synaptogenesis",
    "synaptic plasticity",
    "dendritic spine",
    "spine density",
    "neuritogenesis",
    "neuroplasticity",
    "c-Fos",
    "Fos",
    "Arc",
    "immediate early gene",
    "gene expression",
    "transcriptomic",
    "transcriptome",
    "epigenetic",
    "cytokine",
    "inflammation",
    "inflammatory",
    "cortisol",
    "HPA axis",
    "neuroendocrine",
]

PATHWAY_EVIDENCE_TERMS = [
    "signaling",
    "phosphorylation",
    "expression",
    "protein expression",
    "gene expression",
    "transcriptomics",
    "western blot",
    "qPCR",
    "RNA-seq",
    "immunohistochemistry",
    "ELISA",
    "biomarker",
    "plasticity",
    "synaptic",
    "neuronal",
]

CLINICAL_FUNCTION_SYMPTOM_TERMS = [
    "suicidal ideation",
    "suicidality",
    "anhedonia",
    "craving",
    "withdrawal",
    "relapse",
    "sleep",
    "insomnia",
    "pain intensity",
    "quality of life",
    "wellbeing",
    "well-being",
    "social functioning",
    "occupational functioning",
    "functional impairment",
    "emotional functioning",
    "distress",
]

CLINICAL_FUNCTION_EVIDENCE_TERMS = [
    "clinical trial",
    "randomized",
    "randomised",
    "placebo",
    "open-label",
    "open label",
    "treatment",
    "therapy",
    "outcome",
    "scale",
    "score",
    "follow-up",
    "response",
    "remission",
]

CLINICAL_SAFETY_TERMS = [
    "safety",
    "tolerability",
    "adverse event",
    "adverse events",
    "serious adverse event",
    "side effect",
    "cardiovascular",
    "blood pressure",
    "heart rate",
    "hypertension",
    "mania",
    "psychosis",
    "dissociation",
    "HPPD",
    "hallucinogen persisting perception disorder",
    "flashback",
]

CLINICAL_BRIDGE_TERMS = [
    "depression",
    "major depressive disorder",
    "treatment-resistant depression",
    "PTSD",
    "post-traumatic stress disorder",
    "anxiety",
    "substance use disorder",
    "addiction",
    "alcohol use disorder",
    "opioid use disorder",
    "craving",
    "suicidal ideation",
    "anhedonia",
    "quality of life",
    "patient",
    "patients",
    "clinical outcome",
]

MECHANISM_BRIDGE_TERMS = [
    "fMRI",
    "BOLD",
    "functional connectivity",
    "default mode network",
    "DMN",
    "amygdala",
    "prefrontal cortex",
    "PET",
    "receptor occupancy",
    "EEG",
    "neural oscillations",
    "cognitive task",
    "cognitive flexibility",
    "emotional processing",
    "BDNF",
    "cortisol",
    "cytokine",
    "biomarker",
]

SUBJECTIVE_EXPERIENCE_TERMS = [
    "subjective effects",
    "acute subjective effects",
    "psychedelic experience",
    "subjective drug effects",
    "phenomenology",
    "phenomenological",
    "mystical experience",
    "mystical-type experience",
    "ego dissolution",
    "ego loss",
    "altered state",
    "altered states of consciousness",
    "oceanic boundlessness",
    "visual effects",
    "perceptual effects",
    "hallucinations",
    "hallucinatory effects",
    "emotional breakthrough",
    "challenging experience",
    "anxiety during session",
    "peak experience",
    "psychological insight",
    "self-dissolution",
    "self-transcendence",
    "connectedness",
    "awe",
]

SUBJECTIVE_EXPERIENCE_MEASURE_TERMS = [
    "questionnaire",
    "scale",
    "rating",
    "psychometric",
    "5D-ASC",
    "11D-ASC",
    "5D-OAV",
    "OAV",
    "APZ",
    "ASC",
    "MEQ",
    "MEQ-30",
    "MEQ30",
    "Mystical Experience Questionnaire",
    "Drug Effects Questionnaire",
    "DEQ",
    "Ego-Dissolution Inventory",
    "EDI",
    "Emotional Breakthrough Inventory",
    "EBI",
    "Hallucinogen Rating Scale",
    "HRS",
    "Challenging Experience Questionnaire",
    "CEQ",
    "Psychological Insight Questionnaire",
    "PIQ",
    "Persisting Effects Questionnaire",
    "PEQ",
    "visual analog scale",
    "VAS",
    "acute effects",
]

PHARMACOKINETICS_EXPOSURE_TERMS = [
    "pharmacokinetics",
    "pharmacokinetic",
    "pharmacodynamics",
    "pharmacodynamic",
    "PK/PD",
    "pharmacokinetic-pharmacodynamic",
    "metabolism",
    "metabolite",
    "plasma concentration",
    "serum concentration",
    "blood concentration",
    "plasma level",
    "serum level",
    "blood level",
    "concentration-time",
    "ADME",
    "absorption",
    "distribution",
    "elimination",
    "excretion",
    "urinary excretion",
    "Cmax",
    "Tmax",
    "AUC",
    "half-life",
    "bioavailability",
    "clearance",
    "exposure-response",
    "dose-response",
    "route of administration",
]

PHARMACOKINETICS_EVIDENCE_TERMS = [
    "dose",
    "dosing",
    "administration",
    "concentration",
    "time course",
    "sampling",
    "LC-MS",
    "LC-MS/MS",
    "mass spectrometry",
    "CYP2D6",
    "cytochrome P450",
    "UGT",
    "glucuronidation",
    "glucuronide",
    "MAO-A",
    "monoamine oxidase",
    "protein binding",
    "clinical",
    "human",
    "animal",
]

INTERVENTION_CONTEXT_TERMS = [
    "psychotherapy",
    "preparation",
    "preparation session",
    "integration",
    "integration session",
    "preparation and integration",
    "aftercare",
    "set and setting",
    "set setting",
    "therapeutic alliance",
    "therapeutic relationship",
    "therapist",
    "psychological support",
    "music",
    "music playlist",
    "dosing session",
    "facilitator",
    "manualized therapy",
    "treatment manual",
    "therapist training",
    "facilitator training",
    "supportive therapy",
    "integration therapy",
    "group therapy",
    "expectancy",
    "intention",
    "inner-directed",
    "nondirective support",
    "non-directive support",
    "eyeshades",
    "eye shades",
    "blinding",
]

INTERVENTION_CONTEXT_EVIDENCE_TERMS = [
    "clinical trial",
    "treatment",
    "therapy",
    "protocol",
    "session",
    "outcome",
    "acceptability",
    "feasibility",
    "qualitative",
    "participant",
    "patient",
    "clinical",
]

REAL_WORLD_PUBLIC_HEALTH_TERMS = [
    "epidemiology",
    "prevalence",
    "survey",
    "population",
    "naturalistic",
    "real-world",
    "real world",
    "recreational use",
    "nonmedical use",
    "drug checking",
    "poison center",
    "poison control",
    "emergency department",
    "emergency room",
    "ED visit",
    "harm reduction",
    "public health",
    "community",
    "ceremonial",
    "retreat",
    "microdosing",
    "microdose",
    "self-medication",
    "lifetime use",
    "past-year use",
    "use patterns",
    "non-medical use",
    "adverse experiences",
    "toxicity",
    "hospitalization",
    "misuse",
    "diversion",
]

REAL_WORLD_PUBLIC_HEALTH_EVIDENCE_TERMS = [
    "use",
    "users",
    "risk",
    "adverse",
    "patterns",
    "correlates",
    "longitudinal",
    "cohort",
    "survey",
    "population",
    "outcomes",
    "wellbeing",
    "mental health",
    "harm reduction",
    "observational",
]
